language: node_js
node_js:
  - "lts/*"
cache: yarn
script:
  - yarn setup
  - yarn test
  - yarn deploy
os:
  - linux
  - osx
# Only build tags. TODO: make test and deploy different jobs so test can always run
if: tag IS present